# Generated by Django 2.2 on 2021-08-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockman', '0004_auto_20210814_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='export_to_CSV',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
